name: 'Validate feature'
on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'fix/**'
    paths-ignore:
      - 'Docs/**'
jobs:
  test_push:
    name: 'Test push code on feature branch'
    environment: Dev
    runs-on: ubuntu-latest
    env:
      GH_COMMENT: 'This is a remote test'
      GH_STAGE: 'Push Branch'
      GH_SECRET: ${{ secrets.GH_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cat File
        run: cat message.txt
      - name: Echo Stage
        run: echo $GH_STAGE
      - name: Echo Comment
        run: echo $GH_COMMENT
      - name: Echo Secret
        run: echo $GH_SECRET
      - name: Checkout remote 
        uses: actions/checkout@v2
        with: 
          repository: seldon72/template-action
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.github/template-action
      - name: Run Terraform
        uses: ./.github/template-action/actions/